import { useState } from "react"

export const StringId = {
    MSG_ID_1 : 'MSG_ID_1', 
    MSG_ID_2 : 'MSG_ID_2',
    MSG_ID_3 : 'MSG_ID_3',
    MSG_ID_4 : 'MSG_ID_4',
    MSG_ID_5 : 'MSG_ID_5',
    MSG_ID_6 : 'MSG_ID_6',
    MSG_ID_7 : 'MSG_ID_7',
    MSG_ID_8 : 'MSG_ID_8',
    MSG_ID_9 : 'MSG_ID_9',
    MSG_ID_10 : 'MSG_ID_10',
    MSG_ID_11 : 'MSG_ID_11', 
    MSG_ID_12 : 'MSG_ID_12',
    MSG_ID_13 : 'MSG_ID_13',
    MSG_ID_14 : 'MSG_ID_14',
    MSG_ID_15 : 'MSG_ID_15',
    MSG_ID_16 : 'MSG_ID_16',
    MSG_ID_17 : 'MSG_ID_17',
    MSG_ID_18 : 'MSG_ID_18',
    MSG_ID_19 : 'MSG_ID_19',
    MSG_ID_20 : 'MSG_ID_20',
    MSG_ID_21 : 'MSG_ID_21', 
    MSG_ID_22 : 'MSG_ID_22',
    MSG_ID_23 : 'MSG_ID_23',
    MSG_ID_24 : 'MSG_ID_24',
    MSG_ID_25 : 'MSG_ID_25',
    MSG_ID_26 : 'MSG_ID_26',
    MSG_ID_27 : 'MSG_ID_27',
    MSG_ID_28 : 'MSG_ID_28',
    MSG_ID_29 : 'MSG_ID_29',
    MSG_ID_30 : 'MSG_ID_30',
    MSG_ID_31 : 'MSG_ID_31', 
    MSG_ID_32 : 'MSG_ID_32',
    MSG_ID_33 : 'MSG_ID_33',
    MSG_ID_34 : 'MSG_ID_34',
    MSG_ID_35 : 'MSG_ID_35',
    MSG_ID_36 : 'MSG_ID_36',
    MSG_ID_37 : 'MSG_ID_37',
    MSG_ID_38 : 'MSG_ID_38',
    MSG_ID_39 : 'MSG_ID_39',
    MSG_ID_40 : 'MSG_ID_40',
    MSG_ID_41 : 'MSG_ID_41', 
    MSG_ID_42 : 'MSG_ID_42',
    MSG_ID_43 : 'MSG_ID_43',
    MSG_ID_44 : 'MSG_ID_44',
    MSG_ID_45 : 'MSG_ID_45',
    MSG_ID_46 : 'MSG_ID_46',
    MSG_ID_47 : 'MSG_ID_47',
    MSG_ID_48 : 'MSG_ID_48',
    MSG_ID_49 : 'MSG_ID_49',
    MSG_ID_50 : 'MSG_ID_50',
    MSG_ID_51 : 'MSG_ID_51', 
    MSG_ID_52 : 'MSG_ID_52',
    MSG_ID_53 : 'MSG_ID_53',
    MSG_ID_54 : 'MSG_ID_54',
    MSG_ID_55 : 'MSG_ID_55',
    MSG_ID_56 : 'MSG_ID_56',
    MSG_ID_57 : 'MSG_ID_57',
    MSG_ID_58 : 'MSG_ID_58',
    MSG_ID_59 : 'MSG_ID_59',
    MSG_ID_60 : 'MSG_ID_60',
    MSG_ID_61 : 'MSG_ID_61',
    MSG_ID_62 : 'MSG_ID_62',
    MSG_ID_63 : 'MSG_ID_63',
    MSG_ID_64 : 'MSG_ID_64',
    MSG_ID_65 : 'MSG_ID_65',
    MSG_ID_66 : 'MSG_ID_66',
    MSG_ID_67 : 'MSG_ID_67',
    MSG_ID_68 : 'MSG_ID_68',
    MSG_ID_69 : 'MSG_ID_69',
    MSG_ID_70 : 'MSG_ID_70',
    MSG_ID_71 : 'MSG_ID_71',
    MSG_ID_72 : 'MSG_ID_72',
    MSG_ID_73 : 'MSG_ID_73',
    MSG_ID_74 : 'MSG_ID_74',
    MSG_ID_75 : 'MSG_ID_75',
    MSG_ID_76 : 'MSG_ID_76',
    MSG_ID_77 : 'MSG_ID_77',
    MSG_ID_78 : 'MSG_ID_78',
    MSG_ID_79 : 'MSG_ID_79',
    MSG_ID_80 : 'MSG_ID_80',
    MSG_ID_81 : 'MSG_ID_81',
    MSG_ID_82 : 'MSG_ID_82',
}

export const SpanishStrings = {
    [StringId.MSG_ID_1] : 'Cristobal Rivera Moreno. Ingeniero en sistemas computacionales.',
    [StringId.MSG_ID_2] : 'Ambito educativo',
    [StringId.MSG_ID_3] : 'Ambito laboral',
    [StringId.MSG_ID_4] : 'Ambito personal',
    [StringId.MSG_ID_5] : 'Menu',
    [StringId.MSG_ID_6] : 'Experiencia Laboral',
    [StringId.MSG_ID_7] : 'Proyectos Realizados',
    [StringId.MSG_ID_8] : 'Aspiraciones',
    [StringId.MSG_ID_9] : 'Aguascalientes, México',
    [StringId.MSG_ID_10] : 'Conocimiento',
    [StringId.MSG_ID_11] : 'Habilidades',
    [StringId.MSG_ID_12] : '👋 Hola, mi nombre es Cristobal Rivera Moreno, soy un apasionado por la tenología es por eso que mis aspiraciones se centran en seguirme desarrollando tanto personal como profesionalmente, aprendiendo de las experiencias y de los demás en el mundo tecnológico, y de esta forma apoyar a todo aquel que lo necesite a través de mis habilidades.\nEstoy conciente que las TIC\'s en la actualidad son de suma importancia es por eso que día a día trato de capacitarme con las nuevas novedades sobre un buen manejo de la computación, datos y seguridad de los mismos para seguir innovando en la sociedad.',
    [StringId.MSG_ID_13] : 'Ingeniero de Software',
    [StringId.MSG_ID_14] : 'Feb 2023 - Feb 2024. Grupo Sinco tech and business innnovation.',
    [StringId.MSG_ID_15] : 'Uso de tecnologias como Angular, C#,Laravel(PHP), J Query, javascript .NET, Sql Server y Postgres SQL para desarrollar aplicaciones.',
    [StringId.MSG_ID_16] : 'Asistente En Soporte Técnico (servicio social)',
    [StringId.MSG_ID_17] : 'Ago 2022 - Feb 2023. UAA departamento de redes',
    [StringId.MSG_ID_18] : 'Actividades Asignadas:',
    [StringId.MSG_ID_19] : '<ul><li>✅ Instalar paqueterias y equipos, como: Office, UAA apps y perifericos.</li><li>✅ Apoyar a administrativos en el uso de tecnologias.</li><li>✅ Diagnosticar problemas en sub-redes.</li><li>✅ Mantenimiento a equipos de computo e impresoras.</li></ul>',
    [StringId.MSG_ID_20] : '<ul><li>✅ Analizar requerimientos.</li><li>✅ Uso de SCRUM como framework ágil para desarrollo de sistemas.</li><li>✅ Implementar y proponer funcionalidad basada en los requerimientos.</li><li>✅ Administrar bases de datos.</li></ul>',
    [StringId.MSG_ID_21] : 'Desarrollador De Aplicaciones Mobiles Jr',
    [StringId.MSG_ID_22] : 'En mi estadia he participado en un proyecto destinado al control de aires acondicionados de la empresa Lennox, en el cual he sido miembro del equipo de desarrollo de la plataforma Android.\nUso de tecnologias como: Android Studio, Kotlin, Java, Azure DevOps, BLE (Bluetooth Low Energy) y Wifi Direct.',
    [StringId.MSG_ID_23] : '<ul><li>✅ Solucionar Bugs.\n</li><li>✅ Implementar nuevas funcionalidades.</li><li>\n✅ Analizar logs.\n</li><li>✅ Estar en contacto con el equipo.</li><li>\n✅ </li></ul>',
    [StringId.MSG_ID_24] : 'Feb 2024 - Currently. Krasamo',
    [StringId.MSG_ID_25] : 'C y C++',
    [StringId.MSG_ID_26] : 'Java',
    [StringId.MSG_ID_27] : 'Python',
    [StringId.MSG_ID_28] : 'Javascript',
    [StringId.MSG_ID_29] : 'Typescript',
    [StringId.MSG_ID_30] : 'Angular',
    [StringId.MSG_ID_31] : 'React JS', 
    [StringId.MSG_ID_32] : 'Node JS',
    [StringId.MSG_ID_33] : 'Golang',
    [StringId.MSG_ID_34] : 'C#',
    [StringId.MSG_ID_35] : 'PHP',
    [StringId.MSG_ID_36] : 'Laravel',
    [StringId.MSG_ID_37] : 'HTML',
    [StringId.MSG_ID_38] : 'CSS',
    [StringId.MSG_ID_39] : 'Manejadores de Bases de datos como: SQL Server, PostresSQL y MongoDB',
    [StringId.MSG_ID_40] : 'Arquitectura para APIs Rest Full',
    [StringId.MSG_ID_41] : 'Arquitectura para APIs GraphQL',
    [StringId.MSG_ID_42] : '🧰 Trabajo en equipo',
    [StringId.MSG_ID_43] : '🧰 Proactividad', 
    [StringId.MSG_ID_44] : '🧰 Paciente',
    [StringId.MSG_ID_45] : '🧰 Realista',
    [StringId.MSG_ID_46] : '🧰 Auto critico',
    [StringId.MSG_ID_47] : '🧰 Adaptibilidad a cambios',
    [StringId.MSG_ID_48] : '🧰 Capacidad analitíca',
    [StringId.MSG_ID_49] : '🧰 Curiosidad en temas tecnologicos',
    [StringId.MSG_ID_50] : '© 2023 CRM™. Todos los derechos reservados.',
    [StringId.MSG_ID_51] : 'Contáctame',
    [StringId.MSG_ID_52] : 'Curriculum',
    [StringId.MSG_ID_53] : 'LinkedIn',
    [StringId.MSG_ID_54] : 'Correo',
    [StringId.MSG_ID_55] : 'Github',
    [StringId.MSG_ID_56] : 'Ingles',
    [StringId.MSG_ID_57] : 'Español',
    [StringId.MSG_ID_58] : 'Heroes',
    [StringId.MSG_ID_59] : 'Animalitos a casa',
    [StringId.MSG_ID_60] : 'Pokedex',
    [StringId.MSG_ID_61] : 'Aplicación hecha con Angular. Su finalidad es brindar información relevante sobre distintos heroes de el universo Marvel y DC.',
    [StringId.MSG_ID_62] : 'Aplicación realizada con HTML, css y javascript con fines educativos, destinada a niños.',
    [StringId.MSG_ID_63] : 'Aplicación realizada con React JS y tailwind como framework css, consumiendo API de un servicio web.',
    [StringId.MSG_ID_64] : 'Ing. En sistemas computacionales',
    [StringId.MSG_ID_65] : 'Cursos en Udemy',
    [StringId.MSG_ID_66] : 'Graduado de la carrera de sistemas computacionales en el centro de ciencias básicas de la Universidad Autónoma de Aguascalientes. Durante mi estadia participe en equipos para la realización de proyectos, lo que me ayudo a desarrollar y poner en práctica mis habilidades de comunicación y liderazgo.',
    [StringId.MSG_ID_67] : 'Universidad Autónoma de Aguascalientes',
    [StringId.MSG_ID_68] : 'Junio 2019 - Diciembre 2023',
    [StringId.MSG_ID_69] : 'Cursos hechos en Udemy',
    [StringId.MSG_ID_70] : 'Patrones de diseño de software y principios SOLID.',
    [StringId.MSG_ID_71] : 'Certificado',
    [StringId.MSG_ID_72] : 'Patrones de diseño de software con JS y TS.',
    [StringId.MSG_ID_73] : 'Golang.',
    [StringId.MSG_ID_74] : 'Pasatiempos',
    [StringId.MSG_ID_75] : 'Valores',
    [StringId.MSG_ID_76] : 'Más Sobre Mi',
    [StringId.MSG_ID_77] : 'Smart Tech App',
    [StringId.MSG_ID_78] : 'Aplicación destinada a la instalación de thermostatos Lennox en plataformas Android.',
    [StringId.MSG_ID_79] : 'Home Owner',
    [StringId.MSG_ID_80] : 'Aplicación destinada a la manipulación de thermostatos Lennox a distancia en plataformas Android.',
    [StringId.MSG_ID_81] : 'Prucer',
    [StringId.MSG_ID_82] : 'Aplicación web destinada a certificar productos para el control de agua, regaderas, llaves, etc.'

}


export const EnglishStrings = {
    [StringId.MSG_ID_1] : 'Cristobal Rivera Moreno. Computer Systems Engineer.',
    [StringId.MSG_ID_2] : 'Education Scope',
    [StringId.MSG_ID_3] : 'Professional Scope',
    [StringId.MSG_ID_4] : 'Personal Scope',
    [StringId.MSG_ID_5] : 'Menu',
    [StringId.MSG_ID_6] : 'Career',
    [StringId.MSG_ID_7] : 'Projects Done',
    [StringId.MSG_ID_8] : 'Aspirations',
    [StringId.MSG_ID_9] : 'Experiencia Laboral',
    [StringId.MSG_ID_10] : 'Knowledge',
    [StringId.MSG_ID_11] : 'Skills',
    [StringId.MSG_ID_12] : '👋 Hi, my name is Cristobal Rivera Moreno, I am a technology fanatic that is why my aspirations focuses on keeping improving my skills in the area, learning from experiences and another engineers in the technologic world.\nI am aware of the TIC\'s are currently a great tool to fix problems in the society, therefore, I try keeping updated on the branch and in this way helping people out, putting in practice my insighs.',
    [StringId.MSG_ID_13] : 'Ingeniero de Software',
    [StringId.MSG_ID_14] : 'Feb 2023 Grupo Sinco tech and business innnovationFeb 2023(actúal) Grupo Sinco tech and business innnovation',
    [StringId.MSG_ID_15] : 'Uso de tecnologias como Angular, C#,Laravel(PHP), J Query, javascript .NET, Sql Server y Postgres SQL para desarrollar aplicaciones.',
    [StringId.MSG_ID_16] : 'Asistente En Soporte Técnico (servicio social)',
    [StringId.MSG_ID_17] : 'Ago 2022 - Feb 2023 UAA departamento de redes',
    [StringId.MSG_ID_18] : 'Actividades Asignadas:',
    [StringId.MSG_ID_19] : '✅ Instalar paqueterias y equipos, como: Office, UAA apps y perifericos.\n✅ Apoyar a administrativos en el uso de tecnologias.\n✅ Diagnosticar problemas en sub-redes.\n✅ Mantenimiento a equipos de computo e impresoras.',
    [StringId.MSG_ID_20] : '✅ Analizar requerimientos.\n✅ Uso de SCRUM como framework ágil para desarrollo de sistemas.\n✅ Implementar y proponer funcionalidad basada en los requerimientos.\n✅ Administrar bases de datos.',
    [StringId.MSG_ID_21] : 'Desarrollador De Aplicaciones Mobiles Jr',
    [StringId.MSG_ID_22] : 'En mi estadia he participado en un proyecto destinado al control de aires acondicionados de la empresa Lennox, en el cual he sido miembro del equipo de desarrollo de la plataforma Android.\nUso de tecnologias como: Android Studio, Kotlin, Java, Azure DevOps, BLE (Bluetooth Low Energy) y Wifi Direct.',
    [StringId.MSG_ID_23] : '✅ Solucionar Bugs.\n✅ Implementar nuevas funcionalidades.\n✅ Analizar logs.\n✅ Estar en contacto con el equipo.\n✅ ',
    [StringId.MSG_ID_24] : 'Feb 2024 - Currently',
    [StringId.MSG_ID_25] : 'C y C++',
    [StringId.MSG_ID_26] : 'Java',
    [StringId.MSG_ID_27] : 'Python',
    [StringId.MSG_ID_28] : 'Javascript',
    [StringId.MSG_ID_29] : 'Typescript',
    [StringId.MSG_ID_30] : 'Angular',
    [StringId.MSG_ID_31] : 'React JS', 
    [StringId.MSG_ID_32] : 'Node JS',
    [StringId.MSG_ID_33] : 'Golang',
    [StringId.MSG_ID_34] : 'C#',
    [StringId.MSG_ID_35] : 'PHP',
    [StringId.MSG_ID_36] : 'Laravel',
    [StringId.MSG_ID_37] : 'HTML',
    [StringId.MSG_ID_38] : 'CSS',
    [StringId.MSG_ID_39] : 'Data Base Managements such as: SQL Server, PostresSQL y MongoDB',
    [StringId.MSG_ID_40] : 'Architectures meant for Rest Full API\'s',
    [StringId.MSG_ID_41] : 'Architectures meant for GraphQL API\'s',
    [StringId.MSG_ID_42] : '🧰 Team work',
    [StringId.MSG_ID_43] : '🧰 Proactivity', 
    [StringId.MSG_ID_44] : '🧰 Patient',
    [StringId.MSG_ID_45] : '🧰 Realist',
    [StringId.MSG_ID_46] : '🧰 Self Judgment',
    [StringId.MSG_ID_47] : '🧰 Adaptibility to changes',
    [StringId.MSG_ID_48] : '🧰 Analityc Capacity',
    [StringId.MSG_ID_49] : '🧰 Curiousity on technology topics',
    [StringId.MSG_ID_50] : '© 2023 CRM™. All Rights Reserved.',
    [StringId.MSG_ID_51] : 'Reach me out',
    [StringId.MSG_ID_52] : 'Resume',
    [StringId.MSG_ID_53] : 'LinkedIn',
    [StringId.MSG_ID_54] : 'Email',
    [StringId.MSG_ID_55] : 'Github',
    [StringId.MSG_ID_56] : 'English',
    [StringId.MSG_ID_57] : 'Spanish',
    [StringId.MSG_ID_58] : 'Heroes',
    [StringId.MSG_ID_59] : 'Animals to home',
    [StringId.MSG_ID_60] : 'Pokedex',
    [StringId.MSG_ID_61] : 'Aplication made with Angular. Its objetive is to provide relevant information about distinct heroes from the Marvel & DC universes.',
    [StringId.MSG_ID_62] : 'Aplication made with HTML, css & javascript with purposes of education, meant for children.',
    [StringId.MSG_ID_63] : 'Aplication made with React JS & tailwind as css framework, it consumes an API from a web service.',
    [StringId.MSG_ID_64] : 'Computer System Engineering',
    [StringId.MSG_ID_65] : 'Udemy Courses',
    [StringId.MSG_ID_66] : 'I graduated from the mayor of system computer engineering in the center of basic sciences from the Universidad Autónoma de Aguascalientes. During my journey I got involved with teams to make projects, which helped me develop and put in practice my communication and leading skills.',
    [StringId.MSG_ID_67] : 'Universidad Autónoma de Aguascalientes',
    [StringId.MSG_ID_68] : 'June 2019 - Dec 2023',
    [StringId.MSG_ID_69] : 'Completed Udemy Courses',
    [StringId.MSG_ID_70] : 'Design software patterns and SOLID principles.',
    [StringId.MSG_ID_71] : 'Evidence',
    [StringId.MSG_ID_72] : 'Design software patterns with JS and TS.',
    [StringId.MSG_ID_73] : 'Golang.',
    [StringId.MSG_ID_74] : 'Hobbies',
    [StringId.MSG_ID_75] : 'Values',
    [StringId.MSG_ID_76] : 'More about me',
    [StringId.MSG_ID_77] : 'Smart Tech App',
    [StringId.MSG_ID_78] : 'Aplication meant to install Lennox thermostats on Android platforms.',
    [StringId.MSG_ID_79] : 'Home Owner',
    [StringId.MSG_ID_80] : 'Aplication meant to manage Lennox thermostats from far on Android platforms.',
    [StringId.MSG_ID_81] : 'Prucer',
    [StringId.MSG_ID_82] : 'Web application meant to certificate products for managing the flow of water such as: showers, faucets, etc.'




}



export const getString = (msgId, currLanguage) => {
    if (currLanguage == null) currLanguage = getCurrentLanguage()
    if (currLanguage == "spanish") {
        return SpanishStrings[msgId]
    } else { 
        return EnglishStrings[msgId]
    } 

}

export const getCurrentLanguage = () => localStorage.getItem("language")